channels:
  - conda-forge
dependencies:
  - python=3.9.13
  - pip==22.2.2
  - pip:
  - pip:
    - datagen-tech
    - pandas
    - numpy
    - scikit-learn
    - matplotlib
    - boto3
    - ipykernel
    - aif360